import Vue from 'vue';
import Page from '~/components/bloks/Page.vue';
import Blog from '~/components/bloks/Blog.vue';
import Markdown from '~/components/bloks/Markdown.vue';
import FeaturedGame from '~/components/bloks/FeaturedGame.vue';
import FeaturedArticles from '~/components/bloks/FeaturedArticles.vue';
import Paragraph from '~/components/bloks/Paragraph.vue';
import BlogHeader from '~/components/bloks/BlogHeader.vue';
import BlogImage from '~/components/bloks/BlogImage.vue';
import CodeBlock from '~/components/bloks/CodeBlock.vue';

Vue.component('page', Page);
Vue.component('blog', Blog);
Vue.component('markdown', Markdown);
Vue.component('featured-game', FeaturedGame);
Vue.component('featured-articles', FeaturedArticles);
Vue.component('paragraph', Paragraph);
Vue.component('blog-header', BlogHeader);
Vue.component('blog-image', BlogImage);
Vue.component('code-block', CodeBlock);