import Vue from 'vue';
import Page from '~/components/bloks/Page.vue';
import Blog from '~/components/bloks/Blog.vue';
import Markdown from '~/components/bloks/Markdown.vue';
import FeaturedGame from '~/components/bloks/FeaturedGame.vue';
import FeaturedArticles from '~/components/bloks/FeaturedArticles.vue';
import Paragraph from '~/components/bloks/Paragraph.vue';
import BlogHeader from '~/components/bloks/BlogHeader.vue';
import BlogImage from '~/components/bloks/BlogImage.vue';
import CodeBlock from '~/components/bloks/CodeBlock.vue';
import PageSection from '~/components/bloks/PageSection.vue';
import GameCarousel from '~/components/bloks/GameCarousel.vue';
import GameFeature from '~/components/bloks/GameFeature.vue';
import WelcomeSection from '~/components/bloks/WelcomeSection.vue';
import SectionBlock from '~/components/bloks/SectionBlock.vue';
import SectionText from '~/components/bloks/SectionText.vue';
import SectionImage from '~/components/bloks/SectionImage.vue';
import SectionWelcome from '~/components/bloks/SectionWelcome.vue';
import SectionCard from '~/components/bloks/SectionCard.vue';
import SectionContact from '~/components/bloks/SectionContact.vue';
import SectionCardGrid from '~/components/bloks/SectionCardGrid.vue';
import SectionGridCard from '~/components/bloks/SectionGridCard.vue';

Vue.component('page', Page);
Vue.component('blog', Blog);
Vue.component('markdown', Markdown);
Vue.component('featured-game', FeaturedGame);
Vue.component('featured-articles', FeaturedArticles);
Vue.component('paragraph', Paragraph);
Vue.component('blog-header', BlogHeader);
Vue.component('blog-image', BlogImage);
Vue.component('code-block', CodeBlock);
Vue.component('page-section', PageSection);
Vue.component('game-carousel', GameCarousel);
Vue.component('game-feature', GameFeature);
Vue.component('welcome-section', WelcomeSection);
Vue.component('section-block', SectionBlock);
Vue.component('section-text', SectionText);
Vue.component('section-image', SectionImage);
Vue.component('section-welcome', SectionWelcome);
Vue.component('section-card', SectionCard);
Vue.component('section-contact', SectionContact);
Vue.component('section-card-grid', SectionCardGrid);
Vue.component('section-grid-card', SectionGridCard);